import pandas as pd
import json
import os

def csv_to_js():
    raw_path = "customer_churn_raw.csv"
    clean_path = "customer_churn_clean.csv"
    js_path = "data.js"
    
    if not os.path.exists(raw_path) or not os.path.exists(clean_path):
        print("CSV files not found. Run generate_data.py and data_cleaning.py first.")
        return
        
    df_raw = pd.read_csv(raw_path)
    df_clean = pd.read_csv(clean_path)
    
    # Fill raw NaNs with empty string or null for JSON representation
    df_raw = df_raw.fillna("")
    df_clean = df_clean.fillna("")
    
    raw_list = df_raw.to_dict(orient="records")
    clean_list = df_clean.to_dict(orient="records")
    
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("// Autogenerated from CSV files using generate_js_data.py\n")
        f.write("window.rawCustomerData = ")
        json.dump(raw_list, f, indent=2)
        f.write(";\n\n")
        f.write("window.cleanedCustomerData = ")
        json.dump(clean_list, f, indent=2)
        f.write(";\n")
        
    print(f"Successfully generated JS data file: {js_path}")

if __name__ == "__main__":
    csv_to_js()
